Plan de prueba complemento
hguzman/ADSI2340875 pull request #13
Opened 2022-11-11 05:07 UTC by JimmyCastro01

2022-11-11 16:47 UTC, Jhonmario17 requested changes
Esperar que se apruebe el cambio anterio para poder proceder con el tu yo, despues que lo tengas actualizado

2022-11-17 12:32 UTC, Jhonmario17 approved these changes

2022-11-17 12:51 UTC, Oscarmarquez2003 approved these changes

2022-11-17 14:08 UTC, RonnieRodri approved these changes

2022-11-17 14:08 UTC, RonnieRodri commented
ok

2022-11-17 14:41 UTC, merged