comienzo app movil
hguzman/ADSI2340875 pull request #5
Opened 2022-11-11 03:34 UTC by Josymargeo2909

Por favor revisar y añadir dicho directorio

2022-11-11 16:10 UTC, RonnieRodri approved these changes

2022-11-11 16:10 UTC, RonnieRodri commented
Revisado

2022-11-11 16:44 UTC, Jhonmario17 requested changes
Esperar que se apruebe el cambio anterio para poder proceder con el tu yo despues que lo tengas actualizado

2022-11-17 12:27 UTC, Jhonmario17 approved these changes
Revisado

2022-11-17 12:30 UTC, sugeyberdugo approved these changes
Ok

2022-11-17 12:30 UTC, Oscarmarquez2003 approved these changes

2022-11-17 12:31 UTC, RonnieRodri approved these changes

2022-11-17 12:32 UTC, RonnieRodri commented
Listo

2022-11-17 12:32 UTC, merged