web
hguzman/ADSI2340875 pull request #7
Opened 2022-11-11 04:02 UTC by Oscarmarquez2003

2022-11-11 16:47 UTC, Jhonmario17 requested changes
Esperar que se apruebe el cambio anterio para poder proceder con el tu yo, despues que lo tengas actualizado

2022-11-17 12:33 UTC, Jhonmario17 approved these changes

2022-11-17 12:33 UTC, sugeyberdugo approved these changes
Revisado

2022-11-17 12:33 UTC, RonnieRodri approved these changes

2022-11-17 12:34 UTC, RonnieRodri commented
bien

2022-11-17 12:40 UTC, merged