Documentacion
hguzman/ADSI2340875 pull request #9
Opened 2022-11-11 04:39 UTC by Jireth08

2022-11-11 15:43 UTC, RonnieRodri approved these changes

2022-11-11 15:43 UTC, RonnieRodri commented
Revisado

2022-11-11 16:46 UTC, Jhonmario17 requested changes
Esperar que se apruebe el cambio anterio para poder proceder con el tu yo, despues que lo tengas actualizado

2022-11-17 12:32 UTC, Jhonmario17 approved these changes

2022-11-17 12:39 UTC, sugeyberdugo approved these changes

2022-11-17 12:41 UTC, merged